package com.ssm.mapper;

import com.ssm.entity.Entry;
import com.ssm.entity.EntryExample;
import java.util.List;

public interface EntryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ebook_entry
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ebook_entry
     *
     * @mbg.generated
     */
    int insert(Entry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ebook_entry
     *
     * @mbg.generated
     */
    int insertSelective(Entry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ebook_entry
     *
     * @mbg.generated
     */
    List<Entry> selectByExample(EntryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ebook_entry
     *
     * @mbg.generated
     */
    Entry selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ebook_entry
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Entry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ebook_entry
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Entry record);
}