package com.ssm.entity;

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

public class Entry {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ebook_entry.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ebook_entry.categoryId
     *
     * @mbg.generated
     */
    private Integer categoryid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ebook_entry.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ebook_entry.summary
     *
     * @mbg.generated
     */
    private String summary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ebook_entry.uploadUser
     *
     * @mbg.generated
     */
    private String uploaduser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ebook_entry.createDate
     *
     * @mbg.generated
     */
	@DateTimeFormat(pattern = "yyyy-MM-dd")
	private Date createdate; // 可改成pattern="yyyy-MM-dd  HH:mm:ss"

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ebook_entry.id
     *
     * @return the value of ebook_entry.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ebook_entry.id
     *
     * @param id the value for ebook_entry.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ebook_entry.categoryId
     *
     * @return the value of ebook_entry.categoryId
     *
     * @mbg.generated
     */
    public Integer getCategoryid() {
        return categoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ebook_entry.categoryId
     *
     * @param categoryid the value for ebook_entry.categoryId
     *
     * @mbg.generated
     */
    public void setCategoryid(Integer categoryid) {
        this.categoryid = categoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ebook_entry.title
     *
     * @return the value of ebook_entry.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ebook_entry.title
     *
     * @param title the value for ebook_entry.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ebook_entry.summary
     *
     * @return the value of ebook_entry.summary
     *
     * @mbg.generated
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ebook_entry.summary
     *
     * @param summary the value for ebook_entry.summary
     *
     * @mbg.generated
     */
    public void setSummary(String summary) {
        this.summary = summary == null ? null : summary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ebook_entry.uploadUser
     *
     * @return the value of ebook_entry.uploadUser
     *
     * @mbg.generated
     */
    public String getUploaduser() {
        return uploaduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ebook_entry.uploadUser
     *
     * @param uploaduser the value for ebook_entry.uploadUser
     *
     * @mbg.generated
     */
    public void setUploaduser(String uploaduser) {
        this.uploaduser = uploaduser == null ? null : uploaduser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ebook_entry.createDate
     *
     * @return the value of ebook_entry.createDate
     *
     * @mbg.generated
     */
	public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ebook_entry.createDate
     *
     * @param createdate the value for ebook_entry.createDate
     *
     * @mbg.generated
     */
	public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }
}